default: start

start:
  uv run catalog/main.py

makemigration app:
  uv run piccolo migrations new {{app}} --auto

migrate app="all":
  uv run piccolo migrations forwards {{app}} 

createapp name register="Ture":
  uv run piccolo app new {{name}} --root="./catalog/applications/" --register={{register}}
